"""added username field to user table

Revision ID: 50b07369cc47
Revises: update_schema_002
Create Date: 2025-05-23 20:25:28.280424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b07369cc47'
down_revision: Union[str, None] = 'update_schema_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_domain', table_name='projects')
    op.drop_index('idx_project_user', table_name='projects')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_index('idx_user_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('idx_user_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    op.create_index('idx_project_user', 'projects', ['user_id'], unique=False)
    op.create_index('idx_project_domain', 'projects', ['domain'], unique=False)
    # ### end Alembic commands ###
